# Generated by Django 4.2 on 2023-05-01 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0004_profile_profile_image_alter_twitt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='twitt_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
