# Generated by Django 4.2 on 2023-05-01 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0005_twitt_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='twitt_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
