# Generated by Django 4.2 on 2023-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_twitt_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='twitt_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
